name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: run-tests-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_tests:
    uses: badisi/actions/.github/workflows/action.yml@v3
    with:
      runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node-versions: '[22]'
      lint: true
      test: true
      build: true
